name: Cover Tod
run-name: ${{ github.actor }} Kyaaa
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Installing Bahan Bahan
        run: |
          python -m pip install -U pip wheel
          pip install -U ipython
          pip install -U so-vits-svc-fork
      - run: echo "🍏 This job's status is ${{ job.status }}."
      
      
