name: Cover
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Installing Bahan Bahan
        run: |
          ls ${{ github.workspace }}
       - name: Getting Model
        run: |
          git clone https://huggingface.co/megaaziib/hololivemix-so-vits-svc-4.0
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
      
