name: Cover
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Installing Bahan Bahan
        #run: |
          #python -m pip install -U pip wheel
          #pip install -U ipython
          #ip install -U so-vits-svc-fork
       - name: Installing Bahan Bahan
        run: |
          git clone https://huggingface.co/megaaziib/hololivemix-so-vits-svc-4.0
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
      
