name: Cover
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Intinya Lagi Nginstall App Nya
        run: |
          python -m pip install -U pip wheel
          pip install -U ipython
          pip install -U so-vits-svc-fork
          pip install yt_dlp
          pip install ffmpeg
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: Getting Model
        run: |
          git clone https://huggingface.co/megaaziib/hololivemix-so-vits-svc-4.0
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: Getting Music Base
        run: |
          python -c "from __future__ import unicode_literals; import yt_dlp; import ffmpeg; import sys;
          ydl_opts = {
            'format': 'bestaudio/best',
            'postprocessors': [{
               'key': 'FFmpegExtractAudio',
               'preferredcodec': 'wav', 
            }],
          "outtmpl": 'youtubeaudio/audio',
          }
          def download_from_url(url):
               ydl.download([url])
          with yt_dlp.YoutubeDL(ydl_opts) as ydl:
               url = "https://www.youtube.com/watch?v=cQGfLDnmWS8&pp=ygULYXNtYWxpYnJhc2k%3D" #@param {type:"string"}
               download_from_url(url)"
