# This is a basic workflow to help you get started with Actions

name: Cover

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Installing Bahan Bahan
        run: |
          python -m pip install -U pip wheel
          pip install -U ipython
          pip install -U so-vits-svc-fork
      - run: echo "🍏 This job's status is ${{ job.status }}."
      

